pipeline {
    agent any

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Choose the Terraform action'
        )
    }

    stages {
        stage('Git Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/murthychiluka/CICD-series-1.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Day02-choice-parameters') {
                    sh 'terraform init '
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Day02-choice-parameters') {
                    script {
                        if (params.ACTION == 'apply') {
                            sh 'terraform plan -out=tfplan'
                        } else {
                            sh 'terraform plan -destroy -out=tfplan'
                        }
                    }
                }
            }
        }

        stage('Approval') {
            steps {
                input(
                    message: "Approve Terraform ${params.ACTION}?",
                    ok: "Proceed"
                )
            }
        }

        stage('Terraform Apply/Destroy') {
            steps {
                dir('Day02-choice-parameters') {
                    script {
                        if (params.ACTION == 'apply') {
                            sh 'terraform apply tfplan'
                        } else {
                            sh 'terraform apply tfplan'
                        }
                    }
                }
            }
        }
    }
}